### ISSUE TITLE
Line numbers / file names

### ISSUE THREAD

**Issue by bluescarni** [apolukhin/stacktrace#4]
Would it be possible to add information regarding the line numbers and the filenames related to the functions appearing in the stacktrace?

**Comment by apolukhin** [comment]
It is possible, but very hard to do for all the backends. I'll try to do that for Windows platform soon.

**Comment by bluescarni** [comment]
Ok, thanks for the quick reply!

Out of curiosity, what would be the options on linux/unix platforms? Would stacktrace need to depend on other 3rd party libraries like libdwarf/bfd?

**Comment by apolukhin** [comment]
Do not know exactly, but in case of libdwarf/bfd it will be a separate backend (because of their license).

libdwarf/bfd are GPL which may be unacceptable for some of the library users.

**Comment by eyalroz** [comment]
@apolukhin : You could #ifdef -check their availability, so that's not of a problem I would think...

**Comment by apolukhin** [comment]
Done. There's still room for improvement, however the current solution works out-of-the-box
